version: '3.5'

services:
  hostmanager:
    image: iamluc/docker-hostmanager
    restart: always
    userns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/hosts:/hosts
