version: '3.5'

services:
  hostmanager:
    image: iamluc/docker-hostmanager
    restart: always
    userns_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /c/Windows/System32/drivers/etc/hosts:/hosts

  openvpn:
    cap_add:
      - NET_ADMIN
    image: kylemanna/openvpn
    container_name: vpn
    ports:
      - "1194:1194/udp"
    restart: always
    volumes:
      - ./openvpn-data/conf:/etc/openvpn
    networks:
      - test
      
networks:
  test:
    name: test
