version: "2"
services:
  selenium:
    image: "selenium/standalone-chrome-debug:3.5.2"
    volumes:
        - /dev/shm:/dev/shm
    ports:
        - "${MOODLE_DOCKER_SELENIUM_VNC_PORT}:5900"
    environment:
        # Workaround for https://github.com/SeleniumHQ/docker-selenium/issues/227
        no_proxy: localhost

