version: "3.5"
services:
    selenium:
    image: "selenium/standalone-firefox-debug:2.53.1"
    volumes:
      - "${MOODLE_DOCKER_WWWROOT}:/var/www/html:ro"
    ports:
      - "${MOODLE_DOCKER_SELENIUM_VNC_PORT}:5900"
    environment:
      - "no_proxy": localhost
